import{a as w,S as b,i as n}from"./assets/vendor-D1eTGYtO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L="https://pixabay.com/api/",C="45322930-bdaa0e26907d60cc8a145e4be";async function g(s,r=1,t=16){try{const a=new URLSearchParams({key:C,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:t});return(await w.get(`${L}?${a}`)).data}catch(a){throw new Error(a.response.status)}}const q=document.querySelector(".gallery"),v=new b(".gallery a",{});function h(s){const r=s.map(({webformatURL:t,largeImageURL:a,tags:e,likes:o,views:l,comments:m,downloads:f})=>`
    <div class="card">
    <a href="${a}" >
      <img src="${t}" alt="${e}" /> </a>
      <div class="info">
<ul> 
           <li > <p class="info-name"> Likes: </p> <p>${o}</p></li>
           <li ><p class="info-name"> Views: </p> <p>${l}</p></li>
          <li > <p class="info-name"> Comments: </p> <p>${m}</p></li>
           <li ><p class="info-name"> Downloads: </p> <p>${f}</p></li>
      </ul>
          </div>
          </div>
`);q.insertAdjacentHTML("beforeend",r.join("")),v.refresh()}const y=document.querySelector("#search-form"),P=document.querySelector('input[name="query"]'),i=document.querySelector(".loader"),c=document.querySelector("#load-more");let d=1,p="";const u=16;y.addEventListener("submit",async s=>{s.preventDefault();const r=P.value.trim();if(!r)return n.show({position:"center",backgroundColor:"orange",messageColor:"white",message:"Please fill in a search field."});i.style.display="block",p=r,d=1,gallery.innerHTML="";try{const t=await g(p,d,u);if(i.style.display="none",t.hits.length===0)return c.style.display="none",n.show({position:"topRight",backgroundColor:"red",messageColor:"white",message:"Sorry, there are no images matching your search query. Please try again!"});n.show({position:"topRight",backgroundColor:"green",messageColor:"white",message:`Found ${t.totalHits} results.`}),h(t.hits),y.reset(),t.totalHits>u?c.style.display="block":c.style.display="none"}catch{i.style.display="none",n.show({position:"topRight",backgroundColor:"red",messageColor:"white",message:"Error during the request. Please try again later."})}});c.addEventListener("click",async()=>{d+=1,i.style.display="block";try{const s=await g(p,d,u);if(i.style.display="none",h(s.hits),d*u>=s.totalHits)c.style.display="none",n.show({position:"topRight",backgroundColor:"orange",messageColor:"white",message:"We're sorry, but you've reached the end of search results."});else{const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}catch{i.style.display="none",n.show({position:"topRight",backgroundColor:"red",messageColor:"white",message:"Error during the request. Please try again later."})}});
//# sourceMappingURL=commonHelpers.js.map
